version: '3.7'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: tolumide
            POSTGRES_USER: tolumide
            POSTGRES_DB: diagnosis_backend
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    web:
        image: diagnosis_backend
        depends_on:
            - db
        ports:
            - '4000:4000'
