version: '3.7'
services:
    db:
        image: postgres
        container_name: postgres
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: '${DEV_DB_PASSWORD}'
            POSTGRES_USER: '${DEV_DB_USERNAME}'
            POSTGRES_DB: '${DEV_DB_DATABASE}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5434:5432'
    web:
        build: .
        depends_on:
            - db
        ports:
            - '${PORT}:3000'
        networks:
            - webnet
        environment:
            DB_HOST: db
            PORT: 3000
            DATABASE_URL: ${DATABASE_URL}
        command:
            ['./wait-for-it.sh', 'db:5434', '-t:0', '--', 'npm', 'run', 'start']
networks:
    webnet:
volumes:
    pgdata:
    static_volume:
